---
 
# Authorized Program Facility Services
- name: Authorized Program Facility Services
  collections:
    - ibm.ibm_zos_core
    - ibm.ibm_zos_ims

  block:
    - name: Authorize IMS datasets
      zos_apf:
        force_dynamic: true
        batch:
          - library: '{{ DFS_AUTH_LIB_HLQ1 }}.{{ DFS_AUTH_LIB_HLQ2 }}.SDFSRESL'
            volume: '{{ DFS_DS_VOLUME1 }}'
            sms: '{{DFS_SMS_ENVIRONMENT}}'
          - library: '{{ DFS_AUTH_LIB_HLQ1 }}.{{ DFS_AUTH_LIB_HLQ2 }}.MODBLKS'
            volume: '{{ DFS_DS_VOLUME1 }}'
            sms: '{{DFS_SMS_ENVIRONMENT}}'
          - library: '{{ DFS_AUTH_LIB_HLQ1 }}.{{ DFS_AUTH_LIB_HLQ2 }}.MODBLKSA'
            volume: '{{ DFS_DS_VOLUME1 }}'
            sms: '{{DFS_SMS_ENVIRONMENT}}'
          - library: '{{ DFS_AUTH_LIB_HLQ1 }}.{{ DFS_AUTH_LIB_HLQ2 }}.MODBLKSB'
            volume: '{{ DFS_DS_VOLUME1 }}'
            sms: '{{DFS_SMS_ENVIRONMENT}}'
          - library: '{{ DFS_AUTH_LIB_HLQ1 }}.{{ DFS_AUTH_LIB_HLQ2 }}.EXITLIB'
            volume: '{{ DFS_DS_VOLUME1 }}'
            sms: '{{DFS_SMS_ENVIRONMENT}}'
      register: apf_output
      failed_when:
        # Ignore the error msg "already present in APF" because if this playbook
        # was run before.  The DS are still in APF list.  Other errors should fail
        - apf_output.rc > 0
        - '"already present in APF" not in apf_output.stderr'

      when: auth_datasets
